-- Supabase: execute este SQL no SQL Editor do seu projeto.
create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 40),
  text text not null check (char_length(text) between 1 and 500),
  created_at timestamptz not null default now()
);

alter table public.comments enable row level security;

drop policy if exists "Comentários podem ser lidos por todos" on public.comments;
create policy "Comentários podem ser lidos por todos"
on public.comments for select
using (true);

drop policy if exists "Qualquer visitante pode publicar comentário" on public.comments;
create policy "Qualquer visitante pode publicar comentário"
on public.comments for insert
to anon
with check (char_length(name) between 1 and 40 and char_length(text) between 1 and 500);

-- Não criamos políticas públicas de UPDATE/DELETE.
